NAVLINKS = [
    {"text": "Do gier", "url": "/"},
    {"text": "Do pracy", "url": "/"},
    {"text": "Wszystkie", "url": "/"},
]
FILTERS = [
    {
        "type": "producer",
        "label": "Producent",
        "options": [
            {"label": "Apple", "value": "Apple"},
            {"label": "Dell", "value": "Dell"},
            {"label": "HP", "value": "HP"},
            {"label": "Lenovo", "value": "Lenovo"},
            {"label": "Asus", "value": "Asus"},
            {"label": "Microsoft", "value": "Microsoft"},
            {"label": "Acer", "value": "Acer"},
            {"label": "Razer", "value": "Razer"},
            {"label": "MSI", "value": "MSI"},
            {"label": "Gigabyte", "value": "Gigabyte"},
        ],
    },
    {
        "type": "screen",
        "label": "Ekran",
        "options": [
            {"label": "13.1", "value": "13.1"},
            {"label": "13.4", "value": "13.4"},
            {"label": "13.3", "value": "13.3"},
            {"label": "14", "value": "14"},
            {"label": "15.6", "value": "15.6"},
        ],
    },
    {
        "type": "disk",
        "label": "Dysk",
        "options": [
            {"label": "128GB", "value": "128GB"},
            {"label": "256GB", "value": "256GB"},
            {"label": "512GB", "value": "512GB"},
            {"label": "1TB", "value": "1TB"},
        ],
    },
]
LAPTOPS = [
    {
        "model": "Apple MacBook Air",
        "screen": "13.1",
        "disk": "128GB",
        "ram": "8GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "4825PLN",
        "producer": "Apple",
    },
    {
        "model": "Dell XPS 13",
        "screen": "13.4",
        "disk": "256GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "95%",
        "price": "5899PLN",
        "producer": "Dell",
    },
    {
        "model": "HP Spectre x360",
        "screen": "13.3",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "92%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkPad X1 Carbon",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.09kg",
        "performance": "90%",
        "price": "6999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Asus ROG Zephyrus G14",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.6kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "Asus",
    },
    {
        "model": "Microsoft Surface Laptop 4",
        "screen": "13.5",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.26kg",
        "performance": "93%",
        "price": "7999PLN",
        "producer": "Microsoft",
    },
    {
        "model": "Acer Predator Helios 300",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "96%",
        "price": "8499PLN",
        "producer": "Acer",
    },
    {
        "model": "Razer Blade 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.09kg",
        "performance": "94%",
        "price": "8999PLN",
        "producer": "Razer",
    },
    {
        "model": "MSI GS66 Stealth",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "9499PLN",
        "producer": "MSI",
    },
    {
        "model": "Gigabyte Aero 15 OLED",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Gigabyte",
    },
    {
        "model": "HP Pavilion 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.85kg",
        "performance": "90%",
        "price": "4299PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo IdeaPad 5",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Inspiron 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "3799PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus VivoBook 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Swift 3",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Acer",
    },
    {
        "model": "MSI Modern 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Envy x360",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.1kg",
        "performance": "91%",
        "price": "5499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Legion 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "93%",
        "price": "5799PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell G5 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.68kg",
        "performance": "88%",
        "price": "6499PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus TUF Gaming A15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5799PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Nitro 5",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "89%",
        "price": "5999PLN",
        "producer": "Acer",
    },
    {
        "model": "HP EliteBook 840 G8",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.33kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Yoga C940",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.35kg",
        "performance": "92%",
        "price": "7999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Precision 5550",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "1.84kg",
        "performance": "98%",
        "price": "9999PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus ZenBook Pro Duo",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "10999PLN",
        "producer": "Asus",
    },
    {
        "model": "MSI Prestige 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.29kg",
        "performance": "93%",
        "price": "4999PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Omen 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.36kg",
        "performance": "90%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkBook 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.5kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "New Laptop 1",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.2kg",
        "performance": "95%",
        "price": "7999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 2",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "94%",
        "price": "6999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 3",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "8999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 4",
        "screen": "14",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5499PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 6",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 7",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "4299PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 8",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 9",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 10",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Unknown",
    },
    {
        "model": "Apple MacBook Air",
        "screen": "13.1",
        "disk": "128GB",
        "ram": "8GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "4825PLN",
        "producer": "Apple",
    },
    {
        "model": "Dell XPS 13",
        "screen": "13.4",
        "disk": "256GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "95%",
        "price": "5899PLN",
        "producer": "Dell",
    },
    {
        "model": "HP Spectre x360",
        "screen": "13.3",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "92%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkPad X1 Carbon",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.09kg",
        "performance": "90%",
        "price": "6999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Asus ROG Zephyrus G14",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.6kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "Asus",
    },
    {
        "model": "Microsoft Surface Laptop 4",
        "screen": "13.5",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.26kg",
        "performance": "93%",
        "price": "7999PLN",
        "producer": "Microsoft",
    },
    {
        "model": "Acer Predator Helios 300",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "96%",
        "price": "8499PLN",
        "producer": "Acer",
    },
    {
        "model": "Razer Blade 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.09kg",
        "performance": "94%",
        "price": "8999PLN",
        "producer": "Razer",
    },
    {
        "model": "MSI GS66 Stealth",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "9499PLN",
        "producer": "MSI",
    },
    {
        "model": "Gigabyte Aero 15 OLED",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Gigabyte",
    },
    {
        "model": "HP Pavilion 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.85kg",
        "performance": "90%",
        "price": "4299PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo IdeaPad 5",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Inspiron 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "3799PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus VivoBook 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Swift 3",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Acer",
    },
    {
        "model": "MSI Modern 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Envy x360",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.1kg",
        "performance": "91%",
        "price": "5499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Legion 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "93%",
        "price": "5799PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell G5 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.68kg",
        "performance": "88%",
        "price": "6499PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus TUF Gaming A15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5799PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Nitro 5",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "89%",
        "price": "5999PLN",
        "producer": "Acer",
    },
    {
        "model": "HP EliteBook 840 G8",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.33kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Yoga C940",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.35kg",
        "performance": "92%",
        "price": "7999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Precision 5550",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "1.84kg",
        "performance": "98%",
        "price": "9999PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus ZenBook Pro Duo",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "10999PLN",
        "producer": "Asus",
    },
    {
        "model": "MSI Prestige 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.29kg",
        "performance": "93%",
        "price": "4999PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Omen 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.36kg",
        "performance": "90%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkBook 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.5kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "New Laptop 1",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.2kg",
        "performance": "95%",
        "price": "7999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 2",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "94%",
        "price": "6999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 3",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "8999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 4",
        "screen": "14",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5499PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 6",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 7",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "4299PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 8",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 9",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 10",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Unknown",
    },
    {
        "model": "Apple MacBook Air",
        "screen": "13.1",
        "disk": "128GB",
        "ram": "8GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "4825PLN",
        "producer": "Apple",
    },
    {
        "model": "Dell XPS 13",
        "screen": "13.4",
        "disk": "256GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "95%",
        "price": "5899PLN",
        "producer": "Dell",
    },
    {
        "model": "HP Spectre x360",
        "screen": "13.3",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "92%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkPad X1 Carbon",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.09kg",
        "performance": "90%",
        "price": "6999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Asus ROG Zephyrus G14",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.6kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "Asus",
    },
    {
        "model": "Microsoft Surface Laptop 4",
        "screen": "13.5",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.26kg",
        "performance": "93%",
        "price": "7999PLN",
        "producer": "Microsoft",
    },
    {
        "model": "Acer Predator Helios 300",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "96%",
        "price": "8499PLN",
        "producer": "Acer",
    },
    {
        "model": "Razer Blade 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.09kg",
        "performance": "94%",
        "price": "8999PLN",
        "producer": "Razer",
    },
    {
        "model": "MSI GS66 Stealth",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "9499PLN",
        "producer": "MSI",
    },
    {
        "model": "Gigabyte Aero 15 OLED",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Gigabyte",
    },
    {
        "model": "HP Pavilion 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.85kg",
        "performance": "90%",
        "price": "4299PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo IdeaPad 5",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Inspiron 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "3799PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus VivoBook 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Swift 3",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Acer",
    },
    {
        "model": "MSI Modern 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Envy x360",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.1kg",
        "performance": "91%",
        "price": "5499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Legion 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "93%",
        "price": "5799PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell G5 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.68kg",
        "performance": "88%",
        "price": "6499PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus TUF Gaming A15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5799PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Nitro 5",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "89%",
        "price": "5999PLN",
        "producer": "Acer",
    },
    {
        "model": "HP EliteBook 840 G8",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.33kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Yoga C940",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.35kg",
        "performance": "92%",
        "price": "7999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Precision 5550",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "1.84kg",
        "performance": "98%",
        "price": "9999PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus ZenBook Pro Duo",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "10999PLN",
        "producer": "Asus",
    },
    {
        "model": "MSI Prestige 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.29kg",
        "performance": "93%",
        "price": "4999PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Omen 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.36kg",
        "performance": "90%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkBook 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.5kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "New Laptop 1",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.2kg",
        "performance": "95%",
        "price": "7999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 2",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "94%",
        "price": "6999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 3",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "8999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 4",
        "screen": "14",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5499PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 6",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 7",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "4299PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 8",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 9",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 10",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Unknown",
    },
    {
        "model": "Apple MacBook Air",
        "screen": "13.1",
        "disk": "128GB",
        "ram": "8GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "4825PLN",
        "producer": "Apple",
    },
    {
        "model": "Dell XPS 13",
        "screen": "13.4",
        "disk": "256GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "95%",
        "price": "5899PLN",
        "producer": "Dell",
    },
    {
        "model": "HP Spectre x360",
        "screen": "13.3",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "92%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkPad X1 Carbon",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.09kg",
        "performance": "90%",
        "price": "6999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Asus ROG Zephyrus G14",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.6kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "Asus",
    },
    {
        "model": "Microsoft Surface Laptop 4",
        "screen": "13.5",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.26kg",
        "performance": "93%",
        "price": "7999PLN",
        "producer": "Microsoft",
    },
    {
        "model": "Acer Predator Helios 300",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "96%",
        "price": "8499PLN",
        "producer": "Acer",
    },
    {
        "model": "Razer Blade 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.09kg",
        "performance": "94%",
        "price": "8999PLN",
        "producer": "Razer",
    },
    {
        "model": "MSI GS66 Stealth",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "9499PLN",
        "producer": "MSI",
    },
    {
        "model": "Gigabyte Aero 15 OLED",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Gigabyte",
    },
    {
        "model": "HP Pavilion 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.85kg",
        "performance": "90%",
        "price": "4299PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo IdeaPad 5",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Inspiron 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "3799PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus VivoBook 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Swift 3",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Acer",
    },
    {
        "model": "MSI Modern 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Envy x360",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.1kg",
        "performance": "91%",
        "price": "5499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Legion 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "93%",
        "price": "5799PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell G5 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.68kg",
        "performance": "88%",
        "price": "6499PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus TUF Gaming A15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5799PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Nitro 5",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "89%",
        "price": "5999PLN",
        "producer": "Acer",
    },
    {
        "model": "HP EliteBook 840 G8",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.33kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Yoga C940",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.35kg",
        "performance": "92%",
        "price": "7999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Precision 5550",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "1.84kg",
        "performance": "98%",
        "price": "9999PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus ZenBook Pro Duo",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "10999PLN",
        "producer": "Asus",
    },
    {
        "model": "MSI Prestige 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.29kg",
        "performance": "93%",
        "price": "4999PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Omen 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.36kg",
        "performance": "90%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkBook 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.5kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "New Laptop 1",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.2kg",
        "performance": "95%",
        "price": "7999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 2",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "94%",
        "price": "6999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 3",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "8999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 4",
        "screen": "14",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5499PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 6",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 7",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "4299PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 8",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 9",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 10",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Unknown",
    },
    {
        "model": "Apple MacBook Air",
        "screen": "13.1",
        "disk": "128GB",
        "ram": "8GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "4825PLN",
        "producer": "Apple",
    },
    {
        "model": "Dell XPS 13",
        "screen": "13.4",
        "disk": "256GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "95%",
        "price": "5899PLN",
        "producer": "Dell",
    },
    {
        "model": "HP Spectre x360",
        "screen": "13.3",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "92%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkPad X1 Carbon",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.09kg",
        "performance": "90%",
        "price": "6999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Asus ROG Zephyrus G14",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.6kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "Asus",
    },
    {
        "model": "Microsoft Surface Laptop 4",
        "screen": "13.5",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.26kg",
        "performance": "93%",
        "price": "7999PLN",
        "producer": "Microsoft",
    },
    {
        "model": "Acer Predator Helios 300",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "96%",
        "price": "8499PLN",
        "producer": "Acer",
    },
    {
        "model": "Razer Blade 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.09kg",
        "performance": "94%",
        "price": "8999PLN",
        "producer": "Razer",
    },
    {
        "model": "MSI GS66 Stealth",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "9499PLN",
        "producer": "MSI",
    },
    {
        "model": "Gigabyte Aero 15 OLED",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Gigabyte",
    },
    {
        "model": "HP Pavilion 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.85kg",
        "performance": "90%",
        "price": "4299PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo IdeaPad 5",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Inspiron 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "3799PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus VivoBook 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Swift 3",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Acer",
    },
    {
        "model": "MSI Modern 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Envy x360",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.1kg",
        "performance": "91%",
        "price": "5499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Legion 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "93%",
        "price": "5799PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell G5 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.68kg",
        "performance": "88%",
        "price": "6499PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus TUF Gaming A15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5799PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Nitro 5",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "89%",
        "price": "5999PLN",
        "producer": "Acer",
    },
    {
        "model": "HP EliteBook 840 G8",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.33kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Yoga C940",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.35kg",
        "performance": "92%",
        "price": "7999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Precision 5550",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "1.84kg",
        "performance": "98%",
        "price": "9999PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus ZenBook Pro Duo",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "10999PLN",
        "producer": "Asus",
    },
    {
        "model": "MSI Prestige 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.29kg",
        "performance": "93%",
        "price": "4999PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Omen 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.36kg",
        "performance": "90%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkBook 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.5kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "New Laptop 1",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.2kg",
        "performance": "95%",
        "price": "7999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 2",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "94%",
        "price": "6999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 3",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "8999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 4",
        "screen": "14",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5499PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 6",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 7",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "4299PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 8",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 9",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 10",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Unknown",
    },
    {
        "model": "Apple MacBook Air",
        "screen": "13.1",
        "disk": "128GB",
        "ram": "8GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "4825PLN",
        "producer": "Apple",
    },
    {
        "model": "Dell XPS 13",
        "screen": "13.4",
        "disk": "256GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "95%",
        "price": "5899PLN",
        "producer": "Dell",
    },
    {
        "model": "HP Spectre x360",
        "screen": "13.3",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "92%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkPad X1 Carbon",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.09kg",
        "performance": "90%",
        "price": "6999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Asus ROG Zephyrus G14",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.6kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "Asus",
    },
    {
        "model": "Microsoft Surface Laptop 4",
        "screen": "13.5",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.26kg",
        "performance": "93%",
        "price": "7999PLN",
        "producer": "Microsoft",
    },
    {
        "model": "Acer Predator Helios 300",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "96%",
        "price": "8499PLN",
        "producer": "Acer",
    },
    {
        "model": "Razer Blade 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.09kg",
        "performance": "94%",
        "price": "8999PLN",
        "producer": "Razer",
    },
    {
        "model": "MSI GS66 Stealth",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "9499PLN",
        "producer": "MSI",
    },
    {
        "model": "Gigabyte Aero 15 OLED",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Gigabyte",
    },
    {
        "model": "HP Pavilion 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.85kg",
        "performance": "90%",
        "price": "4299PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo IdeaPad 5",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Inspiron 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "3799PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus VivoBook 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Swift 3",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Acer",
    },
    {
        "model": "MSI Modern 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Envy x360",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.1kg",
        "performance": "91%",
        "price": "5499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Legion 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "93%",
        "price": "5799PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell G5 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.68kg",
        "performance": "88%",
        "price": "6499PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus TUF Gaming A15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5799PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Nitro 5",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "89%",
        "price": "5999PLN",
        "producer": "Acer",
    },
    {
        "model": "HP EliteBook 840 G8",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.33kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Yoga C940",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.35kg",
        "performance": "92%",
        "price": "7999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Precision 5550",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "1.84kg",
        "performance": "98%",
        "price": "9999PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus ZenBook Pro Duo",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "10999PLN",
        "producer": "Asus",
    },
    {
        "model": "MSI Prestige 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.29kg",
        "performance": "93%",
        "price": "4999PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Omen 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.36kg",
        "performance": "90%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkBook 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.5kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "New Laptop 1",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.2kg",
        "performance": "95%",
        "price": "7999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 2",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "94%",
        "price": "6999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 3",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "8999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 4",
        "screen": "14",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5499PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 6",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 7",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "4299PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 8",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 9",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 10",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Unknown",
    },
    {
        "model": "Apple MacBook Air",
        "screen": "13.1",
        "disk": "128GB",
        "ram": "8GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "4825PLN",
        "producer": "Apple",
    },
    {
        "model": "Dell XPS 13",
        "screen": "13.4",
        "disk": "256GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "95%",
        "price": "5899PLN",
        "producer": "Dell",
    },
    {
        "model": "HP Spectre x360",
        "screen": "13.3",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "92%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkPad X1 Carbon",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.09kg",
        "performance": "90%",
        "price": "6999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Asus ROG Zephyrus G14",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.6kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "Asus",
    },
    {
        "model": "Microsoft Surface Laptop 4",
        "screen": "13.5",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.26kg",
        "performance": "93%",
        "price": "7999PLN",
        "producer": "Microsoft",
    },
    {
        "model": "Acer Predator Helios 300",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "96%",
        "price": "8499PLN",
        "producer": "Acer",
    },
    {
        "model": "Razer Blade 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.09kg",
        "performance": "94%",
        "price": "8999PLN",
        "producer": "Razer",
    },
    {
        "model": "MSI GS66 Stealth",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "9499PLN",
        "producer": "MSI",
    },
    {
        "model": "Gigabyte Aero 15 OLED",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Gigabyte",
    },
    {
        "model": "HP Pavilion 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.85kg",
        "performance": "90%",
        "price": "4299PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo IdeaPad 5",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Inspiron 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "3799PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus VivoBook 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Swift 3",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Acer",
    },
    {
        "model": "MSI Modern 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Envy x360",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.1kg",
        "performance": "91%",
        "price": "5499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Legion 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "93%",
        "price": "5799PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell G5 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.68kg",
        "performance": "88%",
        "price": "6499PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus TUF Gaming A15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5799PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Nitro 5",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "89%",
        "price": "5999PLN",
        "producer": "Acer",
    },
    {
        "model": "HP EliteBook 840 G8",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.33kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Yoga C940",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.35kg",
        "performance": "92%",
        "price": "7999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Precision 5550",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "1.84kg",
        "performance": "98%",
        "price": "9999PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus ZenBook Pro Duo",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "10999PLN",
        "producer": "Asus",
    },
    {
        "model": "MSI Prestige 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.29kg",
        "performance": "93%",
        "price": "4999PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Omen 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.36kg",
        "performance": "90%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkBook 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.5kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "New Laptop 1",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.2kg",
        "performance": "95%",
        "price": "7999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 2",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "94%",
        "price": "6999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 3",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "8999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 4",
        "screen": "14",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5499PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 6",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 7",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "4299PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 8",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 9",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 10",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Unknown",
    },
    {
        "model": "Apple MacBook Air",
        "screen": "13.1",
        "disk": "128GB",
        "ram": "8GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "4825PLN",
        "producer": "Apple",
    },
    {
        "model": "Dell XPS 13",
        "screen": "13.4",
        "disk": "256GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "95%",
        "price": "5899PLN",
        "producer": "Dell",
    },
    {
        "model": "HP Spectre x360",
        "screen": "13.3",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "92%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkPad X1 Carbon",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.09kg",
        "performance": "90%",
        "price": "6999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Asus ROG Zephyrus G14",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.6kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "Asus",
    },
    {
        "model": "Microsoft Surface Laptop 4",
        "screen": "13.5",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.26kg",
        "performance": "93%",
        "price": "7999PLN",
        "producer": "Microsoft",
    },
    {
        "model": "Acer Predator Helios 300",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "96%",
        "price": "8499PLN",
        "producer": "Acer",
    },
    {
        "model": "Razer Blade 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.09kg",
        "performance": "94%",
        "price": "8999PLN",
        "producer": "Razer",
    },
    {
        "model": "MSI GS66 Stealth",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "9499PLN",
        "producer": "MSI",
    },
    {
        "model": "Gigabyte Aero 15 OLED",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Gigabyte",
    },
    {
        "model": "HP Pavilion 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.85kg",
        "performance": "90%",
        "price": "4299PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo IdeaPad 5",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Inspiron 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "3799PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus VivoBook 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Swift 3",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Acer",
    },
    {
        "model": "MSI Modern 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Envy x360",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.1kg",
        "performance": "91%",
        "price": "5499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Legion 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "93%",
        "price": "5799PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell G5 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.68kg",
        "performance": "88%",
        "price": "6499PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus TUF Gaming A15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5799PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Nitro 5",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "89%",
        "price": "5999PLN",
        "producer": "Acer",
    },
    {
        "model": "HP EliteBook 840 G8",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.33kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Yoga C940",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.35kg",
        "performance": "92%",
        "price": "7999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Precision 5550",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "1.84kg",
        "performance": "98%",
        "price": "9999PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus ZenBook Pro Duo",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "10999PLN",
        "producer": "Asus",
    },
    {
        "model": "MSI Prestige 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.29kg",
        "performance": "93%",
        "price": "4999PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Omen 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.36kg",
        "performance": "90%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkBook 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.5kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "New Laptop 1",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.2kg",
        "performance": "95%",
        "price": "7999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 2",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "94%",
        "price": "6999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 3",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "8999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 4",
        "screen": "14",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5499PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 6",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 7",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "4299PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 8",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 9",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 10",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Unknown",
    },
    {
        "model": "Apple MacBook Air",
        "screen": "13.1",
        "disk": "128GB",
        "ram": "8GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "4825PLN",
        "producer": "Apple",
    },
    {
        "model": "Dell XPS 13",
        "screen": "13.4",
        "disk": "256GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "95%",
        "price": "5899PLN",
        "producer": "Dell",
    },
    {
        "model": "HP Spectre x360",
        "screen": "13.3",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "92%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkPad X1 Carbon",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.09kg",
        "performance": "90%",
        "price": "6999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Asus ROG Zephyrus G14",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.6kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "Asus",
    },
    {
        "model": "Microsoft Surface Laptop 4",
        "screen": "13.5",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.26kg",
        "performance": "93%",
        "price": "7999PLN",
        "producer": "Microsoft",
    },
    {
        "model": "Acer Predator Helios 300",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "96%",
        "price": "8499PLN",
        "producer": "Acer",
    },
    {
        "model": "Razer Blade 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.09kg",
        "performance": "94%",
        "price": "8999PLN",
        "producer": "Razer",
    },
    {
        "model": "MSI GS66 Stealth",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "9499PLN",
        "producer": "MSI",
    },
    {
        "model": "Gigabyte Aero 15 OLED",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Gigabyte",
    },
    {
        "model": "HP Pavilion 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.85kg",
        "performance": "90%",
        "price": "4299PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo IdeaPad 5",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Inspiron 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "3799PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus VivoBook 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Swift 3",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Acer",
    },
    {
        "model": "MSI Modern 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Envy x360",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.1kg",
        "performance": "91%",
        "price": "5499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Legion 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "93%",
        "price": "5799PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell G5 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.68kg",
        "performance": "88%",
        "price": "6499PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus TUF Gaming A15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5799PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Nitro 5",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "89%",
        "price": "5999PLN",
        "producer": "Acer",
    },
    {
        "model": "HP EliteBook 840 G8",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.33kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Yoga C940",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.35kg",
        "performance": "92%",
        "price": "7999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Precision 5550",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "1.84kg",
        "performance": "98%",
        "price": "9999PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus ZenBook Pro Duo",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "10999PLN",
        "producer": "Asus",
    },
    {
        "model": "MSI Prestige 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.29kg",
        "performance": "93%",
        "price": "4999PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Omen 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.36kg",
        "performance": "90%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkBook 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.5kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "New Laptop 1",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.2kg",
        "performance": "95%",
        "price": "7999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 2",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "94%",
        "price": "6999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 3",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "8999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 4",
        "screen": "14",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5499PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 6",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 7",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "4299PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 8",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 9",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 10",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Unknown",
    },
    {
        "model": "Apple MacBook Air",
        "screen": "13.1",
        "disk": "128GB",
        "ram": "8GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "4825PLN",
        "producer": "Apple",
    },
    {
        "model": "Dell XPS 13",
        "screen": "13.4",
        "disk": "256GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "95%",
        "price": "5899PLN",
        "producer": "Dell",
    },
    {
        "model": "HP Spectre x360",
        "screen": "13.3",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.27kg",
        "performance": "92%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkPad X1 Carbon",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.09kg",
        "performance": "90%",
        "price": "6999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Asus ROG Zephyrus G14",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.6kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "Asus",
    },
    {
        "model": "Microsoft Surface Laptop 4",
        "screen": "13.5",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.26kg",
        "performance": "93%",
        "price": "7999PLN",
        "producer": "Microsoft",
    },
    {
        "model": "Acer Predator Helios 300",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "96%",
        "price": "8499PLN",
        "producer": "Acer",
    },
    {
        "model": "Razer Blade 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.09kg",
        "performance": "94%",
        "price": "8999PLN",
        "producer": "Razer",
    },
    {
        "model": "MSI GS66 Stealth",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "9499PLN",
        "producer": "MSI",
    },
    {
        "model": "Gigabyte Aero 15 OLED",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Gigabyte",
    },
    {
        "model": "HP Pavilion 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.85kg",
        "performance": "90%",
        "price": "4299PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo IdeaPad 5",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Inspiron 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "3799PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus VivoBook 15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Swift 3",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Acer",
    },
    {
        "model": "MSI Modern 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Envy x360",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.1kg",
        "performance": "91%",
        "price": "5499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Legion 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "93%",
        "price": "5799PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell G5 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.68kg",
        "performance": "88%",
        "price": "6499PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus TUF Gaming A15",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5799PLN",
        "producer": "Asus",
    },
    {
        "model": "Acer Nitro 5",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "89%",
        "price": "5999PLN",
        "producer": "Acer",
    },
    {
        "model": "HP EliteBook 840 G8",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.33kg",
        "performance": "95%",
        "price": "7499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo Yoga C940",
        "screen": "14",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "1.35kg",
        "performance": "92%",
        "price": "7999PLN",
        "producer": "Lenovo",
    },
    {
        "model": "Dell Precision 5550",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "1.84kg",
        "performance": "98%",
        "price": "9999PLN",
        "producer": "Dell",
    },
    {
        "model": "Asus ZenBook Pro Duo",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.5kg",
        "performance": "97%",
        "price": "10999PLN",
        "producer": "Asus",
    },
    {
        "model": "MSI Prestige 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.29kg",
        "performance": "93%",
        "price": "4999PLN",
        "producer": "MSI",
    },
    {
        "model": "HP Omen 15",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.36kg",
        "performance": "90%",
        "price": "6499PLN",
        "producer": "HP",
    },
    {
        "model": "Lenovo ThinkBook 14",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.5kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Lenovo",
    },
    {
        "model": "New Laptop 1",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "16GB",
        "weight": "2.2kg",
        "performance": "95%",
        "price": "7999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 2",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "94%",
        "price": "6999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 3",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.1kg",
        "performance": "98%",
        "price": "8999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 4",
        "screen": "14",
        "disk": "1TB",
        "ram": "32GB",
        "weight": "2.2kg",
        "performance": "97%",
        "price": "9999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 5",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "2.3kg",
        "performance": "90%",
        "price": "5499PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 6",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.6kg",
        "performance": "88%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 7",
        "screen": "15.6",
        "disk": "1TB",
        "ram": "8GB",
        "weight": "2.2kg",
        "performance": "85%",
        "price": "4299PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 8",
        "screen": "15.6",
        "disk": "512GB",
        "ram": "8GB",
        "weight": "1.8kg",
        "performance": "86%",
        "price": "2999PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 9",
        "screen": "14",
        "disk": "256GB",
        "ram": "8GB",
        "weight": "1.5kg",
        "performance": "89%",
        "price": "3799PLN",
        "producer": "Unknown",
    },
    {
        "model": "New Laptop 10",
        "screen": "14",
        "disk": "512GB",
        "ram": "16GB",
        "weight": "1.3kg",
        "performance": "92%",
        "price": "4499PLN",
        "producer": "Unknown",
    },
]


if __name__ == "__main__":
    a = LAPTOPS * 10
    print()
